name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.2.0'

      # - name: Build and install dependencies
      #   run: npm install && npm run build
      - name: Set permissions for appleboy ssh action
        run: chmod +x /var/run/act/actions/appleboy-ssh-action@master/entrypoint.sh

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: 22
          script: |
            cd /opt/bitnami/projects/github-actions-test
            git pull
            npm install
            npm run build

      - name: Deployment completed Successfully
        run: echo "Deployment completed successfuly"
