name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.2.0'

      - name: Install Node.js dependencies
        run: npm install

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: easingthemes/ssh-deploy@v5.1.1
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          EXCLUDE: ".git*,node_modules,.next"
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "."
          TARGET: "/opt/bitnami/projects/github-actions-test" # Specify the path to your app directory on the server
          SCRIPT_AFTER: |
            git pull
            npm install
            npm run build
