name: "Deploy to Server"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Install Node.js"
				uses: actions/setup-node@v2
				with:
					node-version: "22.2.0"

      - name: "Synchronize Files to Server"
        uses: "easingthemes/ssh-deploy@v2.1.5"
        env:
					SOURCE: "."
					SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /opt/bitnami/projects/github-actions-test
          
      - name: "Run remote commands"
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/bitnami/projects/github-actions-test
            npm run build
