name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger deployments from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'  # Set to your Node.js version

      - name: Install dependencies
        run: npm install

      # - name: Build Next.js app
      #   run: npm run build

      # - name: Archive production files
      #   run: tar -czf build.tar.gz .next package.json
      
      # - name: Check SSH Key Access
      #   run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -c

      # - name: Debug User Value
      #   run: echo " Lightsail User = ${{ secrets.REMOTE_USER }}"

      # - name: Debug Host Value
      #   run: echo " Lightsail Host = ${{ secrets.REMOTE_HOST }}"

      # - name: Upload build to Lightsail
      #   uses: appleboy/scp-action@v0.1.5
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: build.tar.gz
      #     target: /opt/bitnami/projects/github-actions-test  # Change to your project directory on the Lightsail instance

      - name: SSH and Deploy on Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -al /opt/bitnami/projects/github-actions-test
            cd /opt/bitnami/projects/github-actions-test
            node -v
